apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.class: elasticity
  enable: true
  name: product-reports
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: product-reports
